#!/usr/bin/env python3
"""Regenerate Tests/Fixtures/Archive/v1.sqlite.

The fixture is a frozen v1 archive: the schema exactly as the shipped
``v1_initial`` and ``v1_fts`` migrations create it, populated with synthetic
rows, with GRDB's ``grdb_migrations`` bookkeeping table marking both migrations
as applied. ``ArchiveMigrationTests`` opens a copy of it through ``Archive`` to
prove that a database written by an older build still migrates and keeps its
rows.

The schema is *extracted from* ``ArchiveMigrations.swift`` rather than restated
here, so the fixture cannot drift from the migration that produced it. The rows
come from a seeded LCG, so regenerating produces the same file.

    python3 Tests/Fixtures/Archive/make_v1.py

Everything in this file is invented. Per the project's privacy invariants a
fixture never contains real notification content, real senders, or a real
one-time code — see docs/testing/TESTING.md, "Test data hygiene checklist".
Do not regenerate this fixture against a real archive, ever.
"""

from __future__ import annotations

import pathlib
import re
import sqlite3
import subprocess
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parents[3]
MIGRATIONS = ROOT / "Packages/BackglanceCore/Sources/BackglanceCore/Archive/ArchiveMigrations.swift"
OUTPUT = ROOT / "Tests/Fixtures/Archive/v1.sqlite"

SEED = 20260819
APPS = [
    # bundle_id, display_name, retention, is_excluded, is_muted, redact_otp
    ("com.example.chat", "Example Chat", "inherit", 0, 0, 1),
    ("com.example.mailer", "Example Mail", "30d", 0, 0, 1),
    ("com.example.builder", "Example Build", "7d", 0, 1, 0),
    ("com.example.vault", "Example Vault", "never", 1, 0, 0),
    ("com.example.calendar", "Example Cal", "inherit", 0, 0, 0),
]
TITLES = ["Build finished", "Standup in 10 minutes", "Deploy queued", "Weekly report ready", "New comment"]
BODIES = [
    "Everything is synthetic here.",
    "Placeholder body text for the fixture.",
    "No real content in this file.",
    "Generated by a seeded script.",
    "Fixture row, safe to read.",
]
SENDERS = ["Sample Sender", "Fixture Bot", "Test Account", "Placeholder Name", "Synthetic User"]
BASE_TIME = 1_700_000_000
ROW_COUNT = 24


def schema_sql() -> str:
    """The v1 DDL, read straight out of the shipped migrations."""
    source = MIGRATIONS.read_text()
    parts = []
    for name in ("v1InitialSQL", "ftsTableSQL", "ftsTriggersSQL"):
        match = re.search(r'static let %s = """\n(.*?)\n\s*"""' % name, source, re.S)
        if match is None:
            sys.exit(f"could not find {name} in {MIGRATIONS}")
        parts.append(textwrap.dedent(match.group(1)))
    return "\n".join(parts)


def main() -> None:
    if OUTPUT.exists():
        OUTPUT.unlink()

    db = sqlite3.connect(OUTPUT)
    db.executescript(schema_sql())

    for index, (bundle_id, name, retention, excluded, muted, redact_otp) in enumerate(APPS):
        first_seen = BASE_TIME + index * 3600
        db.execute(
            "INSERT INTO apps(bundle_id, display_name, retention, is_excluded, is_muted, redact_otp,"
            " first_seen_at, last_seen_at, notification_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)",
            (bundle_id, name, retention, excluded, muted, redact_otp, first_seen, first_seen + 7200),
        )

    state = SEED

    def rnd(bound: int) -> int:
        nonlocal state
        state = (state * 1103515245 + 12345) % (2**31)
        return state % bound

    for index in range(ROW_COUNT):
        delivered = BASE_TIME + index * 900
        db.execute(
            "INSERT INTO notifications(uuid, app_id, title, subtitle, body, sender, thread_id, category,"
            " delivered_at, captured_at, source, presented, is_deleted, store_rec_id)"
            " VALUES (?, ?, ?, NULL, ?, ?, ?, 'general', ?, ?, 'import', ?, ?, ?)",
            (
                f"00000000-0000-4000-8000-{index:012d}",
                (index % len(APPS)) + 1,
                TITLES[rnd(len(TITLES))],
                BODIES[rnd(len(BODIES))],
                SENDERS[rnd(len(SENDERS))],
                f"thread-{index % 4}",
                delivered,
                delivered + 2,
                0 if index % 7 == 0 else 1,
                1 if index % 11 == 0 else 0,
                1000 + index,
            ),
        )

    db.execute(
        "INSERT INTO away_sessions(started_at, ended_at, reason) VALUES (?, ?, 'locked')",
        (BASE_TIME + 3600, BASE_TIME + 7200),
    )
    db.execute(
        "INSERT INTO rules(kind, pattern, match_field, priority, is_enabled, created_at)"
        " VALUES ('highlight', 'deploy', 'any', 1, 1, ?)",
        (BASE_TIME,),
    )
    db.execute("INSERT INTO capture_state(key, value) VALUES ('adapter_id', 'v26')")
    db.execute("INSERT INTO schema_meta(key, value) VALUES ('archive_version', '1')")
    db.execute(
        "UPDATE apps SET notification_count ="
        " (SELECT count(*) FROM notifications n WHERE n.app_id = apps.id)"
    )

    # GRDB's own bookkeeping: without these rows the migrator would try to run
    # v1_initial again on a database that already has the tables.
    db.execute("CREATE TABLE IF NOT EXISTS grdb_migrations (identifier TEXT NOT NULL PRIMARY KEY)")
    db.executemany("INSERT INTO grdb_migrations(identifier) VALUES (?)", [("v1_initial",), ("v1_fts",)])

    db.execute("INSERT INTO notifications_fts(notifications_fts) VALUES ('rebuild')")
    db.commit()
    db.execute("VACUUM")

    for statement in ("PRAGMA integrity_check", "PRAGMA foreign_key_check"):
        rows = db.execute(statement).fetchall()
        if rows not in ([("ok",)], []):
            sys.exit(f"{statement} failed on the generated fixture: {rows}")
    db.close()

    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    subprocess.run(["git", "diff", "--stat", "--", str(OUTPUT)], cwd=ROOT, check=False)


if __name__ == "__main__":
    main()
