// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "BackglanceCapture",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "BackglanceCapture", targets: ["BackglanceCapture"]),
    ],
    dependencies: [
        .package(path: "../../Tests/BackglanceTestSupport"),
        .package(path: "../BackglanceCore"),
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "7.0.0"),
    ],
    targets: [
        .target(
            name: "BackglanceCapture",
            dependencies: [
                "BackglanceCore",
                .product(name: "GRDB", package: "GRDB.swift"),
            ],
            resources: [
                .copy("Resources/KnownFingerprints.json"), // regenerated by Scripts/verify_fixture.sh
            ],
            swiftSettings: [
                .enableUpcomingFeature("StrictConcurrency"),
            ]
        ),
        .executableTarget(
            name: "FixtureGenerator",
            dependencies: ["BackglanceCapture"],
            swiftSettings: [
                .enableUpcomingFeature("StrictConcurrency"),
            ]
        ),
        .testTarget(
            name: "BackglanceCaptureTests",
            dependencies: ["BackglanceCapture", "BackglanceTestSupport"],
            path: "Tests/BackglanceCaptureTests",
            // Tests/Fixtures is symlinked into every bundle as SharedFixtures, so this
            // target sees the archive fixtures too. They belong to BackglanceCoreTests;
            // bundling them here would ship a copy nothing reads.
            exclude: ["SharedFixtures/Archive"],
            resources: [
                .copy("SharedFixtures/SystemStore"), // macOS14/, macOS15/, macOS26/ — synthetic only
            ]
        ),
    ]
)
